name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: snd2Deployment
    type: boolean
    default: true
  - name: snd1Deployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: branch-name

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    failOnThreshold: high  # Optional: moderate (default), low, high, critical
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.snd2Deployment }}
    snd1Deployment: ${{ parameters.snd1Deployment }}
    variableGroupName: ffc-doc-statement-data-env-var
    pr_params:
      container.delinkedEnabled: $(pr_delinkedEnabled)
      container.demographicsActive: $(pr_demographicsActive)
      container.excludeCalculationData: $(pr_excludeCalculationData)
      container.publishingEnabled: $(pr_publishingEnabled)
      container.sfi23Enabled: $(pr_sfi23Enabled)
      container.useNewDWHContainer: $(pr_useNewDWHContainer)
      container.fakeData: $(pr_fakeData)
      container.subsetProcessDelinked: $(pr_subsetProcessDelinked)
      container.subsetProcessSfi23: $(pr_subsetProcessSfi23)
      container.processDelinkedSubsetAmount: $(pr_processDelinkedSubsetAmount)
      container.processSfi23SubsetAmount: $(pr_processSfi23SubsetAmount)
      container.pollingInterval: $(pr_pollingInterval)
      container.day0DateTime: $(pr_day0DateTime)
      container.pollWindowEnabled: $(pr_pollWindowEnabled)
      container.pollWindowStart: $(pr_pollWindowStart)
      container.pollWindowEnd: $(pr_pollWindowEnd)
      container.pollWindowDays: $(pr_pollWindowDays)
    snd1_params:
      container.delinkedEnabled: $(snd1_delinkedEnabled)
      container.demographicsActive: $(snd1_demographicsActive)
      container.excludeCalculationData: $(snd1_excludeCalculationData)
      container.publishingEnabled: $(snd1_publishingEnabled)
      container.sfi23Enabled: $(snd1_sfi23Enabled)
      container.useNewDWHContainer: $(snd1_useNewDWHContainer)
      container.fakeData: $(snd1_fakeData)
      container.subsetProcessDelinked: $(snd1_subsetProcessDelinked)
      container.subsetProcessSfi23: $(snd1_subsetProcessSfi23)
      container.processDelinkedSubsetAmount: $(snd1_processDelinkedSubsetAmount)
      container.processSfi23SubsetAmount: $(snd1_processSfi23SubsetAmount)
      container.pollingInterval: $(snd1_pollingInterval)
      container.day0DateTime: $(snd1_day0DateTime)
      container.pollWindowEnabled: $(snd1_pollWindowEnabled)
      container.pollWindowStart: $(snd1_pollWindowStart)
      container.pollWindowEnd: $(snd1_pollWindowEnd)
      container.pollWindowDays: $(snd1_pollWindowDays)
    snd2_params:
      container.delinkedEnabled: $(snd2_delinkedEnabled)
      container.demographicsActive: $(snd2_demographicsActive)
      container.excludeCalculationData: $(snd2_excludeCalculationData)
      container.publishingEnabled: $(snd2_publishingEnabled)
      container.sfi23Enabled: $(snd2_sfi23Enabled)
      container.useNewDWHContainer: $(snd2_useNewDWHContainer)
      container.fakeData: $(snd2_fakeData)
      container.subsetProcessDelinked: $(snd2_subsetProcessDelinked)
      container.subsetProcessSfi23: $(snd2_subsetProcessSfi23)
      container.processDelinkedSubsetAmount: $(snd2_processDelinkedSubsetAmount)
      container.processSfi23SubsetAmount: $(snd2_processSfi23SubsetAmount)
      container.pollingInterval: $(snd2_pollingInterval)
      container.day0DateTime: $(snd2_day0DateTime)
      container.pollWindowEnabled: $(snd2_pollWindowEnabled)
      container.pollWindowStart: $(snd2_pollWindowStart)
      container.pollWindowEnd: $(snd2_pollWindowEnd)
      container.pollWindowDays: $(snd2_pollWindowDays)
    dev_params:
      container.delinkedEnabled: $(dev_delinkedEnabled)
      container.demographicsActive: $(dev_demographicsActive)
      container.excludeCalculationData: $(dev_excludeCalculationData)
      container.publishingEnabled: $(dev_publishingEnabled)
      container.sfi23Enabled: $(dev_sfi23Enabled)
      container.useNewDWHContainer: $(dev_useNewDWHContainer)
      container.fakeData: $(dev_fakeData)
      container.subsetProcessDelinked: $(dev_subsetProcessDelinked)
      container.subsetProcessSfi23: $(dev_subsetProcessSfi23)
      container.processDelinkedSubsetAmount: $(dev_processDelinkedSubsetAmount)
      container.processSfi23SubsetAmount: $(dev_processSfi23SubsetAmount)
      container.pollingInterval: $(dev_pollingInterval)
      container.day0DateTime: $(dev_day0DateTime)
      container.pollWindowEnabled: $(dev_pollWindowEnabled)
      container.pollWindowStart: $(dev_pollWindowStart)
      container.pollWindowEnd: $(dev_pollWindowEnd)
      container.pollWindowDays: $(dev_pollWindowDays)
    test_params:
      container.delinkedEnabled: $(test_delinkedEnabled)
      container.demographicsActive: $(test_demographicsActive)
      container.excludeCalculationData: $(test_excludeCalculationData)
      container.publishingEnabled: $(test_publishingEnabled)
      container.sfi23Enabled: $(test_sfi23Enabled)
      container.useNewDWHContainer: $(test_useNewDWHContainer)
      container.fakeData: $(test_fakeData)
      container.subsetProcessDelinked: $(test_subsetProcessDelinked)
      container.subsetProcessSfi23: $(test_subsetProcessSfi23)
      container.processDelinkedSubsetAmount: $(test_processDelinkedSubsetAmount)
      container.processSfi23SubsetAmount: $(test_processSfi23SubsetAmount)
      container.pollingInterval: $(test_pollingInterval)
      container.day0DateTime: $(test_day0DateTime)
      container.pollWindowEnabled: $(test_pollWindowEnabled)
      container.pollWindowStart: $(test_pollWindowStart)
      container.pollWindowEnd: $(test_pollWindowEnd)
      container.pollWindowDays: $(test_pollWindowDays)
    pre_params:
      container.delinkedEnabled: $(pre_delinkedEnabled)
      container.demographicsActive: $(pre_demographicsActive)
      container.excludeCalculationData: $(pre_excludeCalculationData)
      container.publishingEnabled: $(pre_publishingEnabled)
      container.sfi23Enabled: $(pre_sfi23Enabled)
      container.useNewDWHContainer: $(pre_useNewDWHContainer)
      container.fakeData: $(pre_fakeData)
      container.subsetProcessDelinked: $(pre_subsetProcessDelinked)
      container.subsetProcessSfi23: $(pre_subsetProcessSfi23)
      container.processDelinkedSubsetAmount: $(pre_processDelinkedSubsetAmount)
      container.processSfi23SubsetAmount: $(pre_processSfi23SubsetAmount)
      container.pollingInterval: $(pre_pollingInterval)
      container.day0DateTime: $(pre_day0DateTime)
      container.pollWindowEnabled: $(pre_pollWindowEnabled)
      container.pollWindowStart: $(pre_pollWindowStart)
      container.pollWindowEnd: $(pre_pollWindowEnd)
      container.pollWindowDays: $(pre_pollWindowDays)
    prd_params:
      container.delinkedEnabled: $(prd_delinkedEnabled)
      container.demographicsActive: $(prd_demographicsActive)
      container.excludeCalculationData: $(prd_excludeCalculationData)
      container.publishingEnabled: $(prd_publishingEnabled)
      container.sfi23Enabled: $(prd_sfi23Enabled)
      container.useNewDWHContainer: $(prd_useNewDWHContainer)
      container.fakeData: $(prd_fakeData)
      container.subsetProcessDelinked: $(prd_subsetProcessDelinked)
      container.subsetProcessSfi23: $(prd_subsetProcessSfi23)
      container.processDelinkedSubsetAmount: $(prd_processDelinkedSubsetAmount)
      container.processSfi23SubsetAmount: $(prd_processSfi23SubsetAmount)
      container.pollingInterval: $(prd_pollingInterval)
      container.day0DateTime: $(prd_day0DateTime)
      container.pollWindowEnabled: $(prd_pollWindowEnabled)
      container.pollWindowStart: $(prd_pollWindowStart)
      container.pollWindowEnd: $(prd_pollWindowEnd)
      container.pollWindowDays: $(prd_pollWindowDays)
