# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-doc-statement-data:
    build:
      target: development
    image: ffc-doc-statement-data-development
    container_name: ffc-doc-statement-data-development
    ports:
      - "9282:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-doc-statement-data-azurite:10000/devstoreaccount1;
    depends_on:
      - ffc-doc-statement-data-azurite

  ffc-doc-statement-data-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10068:10000"

  ffc-doc-statement-data-postgres:
    ports:
      - "5482:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  azurite_data:
  postgres_data:
