# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-doc-statement-data:
    build:
      target: development
    image: ffc-doc-statement-data-development
    container_name: ffc-doc-statement-data-development
    ports:
      - "9282:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-doc-statement-data-postgres:
    ports:
      - "5482:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
