version: '3.8'
services:
  ffc-doc-statement-data:
    build:
      context: .
      target: production
    image: ffc-doc-statement-data
    container_name: ffc-doc-statement-data
    depends_on:
      - ffc-doc-statement-data-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-doc-statement-data-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      DATA_TOPIC_ADDRESS: ${DATA_TOPIC_ADDRESS:-ffc-doc-statement-data}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_pay_statement_data
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-doc-statement-data-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  ffc-doc-statement-data-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_pay_statement_data
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
