environment: development
environmentCode:
name: ffc-doc-statement-data
namespace: ffc-doc
workstream: ffc-doc
image: ffc-doc-statement-data

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-doc-statement-data-config-map

containerSecret:
  name: ffc-doc-statement-data-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: Always
  requestMemory: 150Mi
  requestCpu: 120m
  limitMemory: 150Mi
  limitCpu: 180m
  messageQueueHost: namespace.servicebus.windows.net
  dataTopicAddress: ffc-doc-statement-data

postgresService:
  postgresDb: ffc_doc_statement_data
  postgresqlHost: ffc-doc-statement-data-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

cronJob:
  schedule: "*/10 * * * *"
  resultsAllSchedule: "0 0 1 * *"
  concurrencyPolicy: Forbid
  restartPolicy: Never
