environment: development
environmentCode:
name: ffc-doc-statement-data
namespace: ffc-doc
workstream: ffc-doc
image: ffc-doc-statement-data

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-doc-statement-data-config-map

containerSecret:
  name: ffc-doc-statement-data-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 50
  memoryThreshold: 70

container:
  requestMemory: 1024Mi
  requestCpu: 900m
  limitMemory: 1024Mi
  limitCpu: 1700m
  messageQueueHost: namespace.servicebus.windows.net
  dataTopicAddress: ffc-doc-statement-data
  alertTopicAddress: ffc-doc-alerting
  demographicsTopicAddress: ffc-pay-demographics-extract
  demographicsSubscriptionAddress: ffc-doc-demographics
  azureStorageConnectionString: dummy
  azureStorageAccountName: ffcdoc
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  demographicsActive: true
  etlProcessTopicErrorAddress: ffc-doc-alerting
  excludeCalculationData: true
  sfi23Enabled: true
  delinkedEnabled: true
  fakeData: true
  subsetProcessDelinked: false
  subsetProcessSfi23: false
  processDelinkedSubsetAmount: 10
  processSfi23SubsetAmount: 10
  publishingEnabled: true
  logIntervalMs: 60000
  pollingInterval: 3600000
  day0DateTime: 2099-12-31T00:00:00Z

postgresService:
  postgresDb: ffc_doc_statement_data
  postgresqlHost: ffc-doc-statement-data-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
