environment: development
environmentCode:
name: ffc-doc-statement-data
namespace: ffc-doc
workstream: ffc-doc
image: ffc-doc-statement-data

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-doc-statement-data-config-map

containerSecret:
  name: ffc-doc-statement-data-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 50
  memoryThreshold: 70

container:
  requestMemory: 300Mi
  requestCpu: 240m
  limitMemory: 300Mi
  limitCpu: 360m
  messageQueueHost: namespace.servicebus.windows.net
  dataTopicAddress: ffc-doc-statement-data
  demographicsTopicAddress: ffc-pay-demographics-extract
  demographicsSubscriptionAddress: ffc-doc-demographics
  demographicsActive: true

postgresService:
  postgresDb: ffc_doc_statement_data
  postgresqlHost: ffc-doc-statement-data-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
