module.exports = {
  appCalculationResultsDelinkPayments: 'etlStageAppCalcResultsDelinkPayments',
  applicationDetail: 'etlStageApplicationDetail',
  applicationDetailDelinked: 'etlStageApplicationDetail',
  appsPaymentNotification: 'etlStageAppsPaymentNotification',
  appsPaymentNotificationDelinked: 'etlStageAppsPaymentNotification',
  appsTypes: 'etlStageAppsTypes',
  businessAddress: 'etlStageBusinessAddressContactV',
  businessAddressDelinked: 'etlStageBusinessAddressContactV',
  calculationsDetails: 'etlStageCalculationDetails',
  calculationsDetailsDelinked: 'etlStageCalculationDetails',
  cssContractApplications: 'etlStageCssContractApplications',
  cssContract: 'etlStageCssContracts',
  cssOptions: 'etlStageCssOptions',
  defraLinks: 'etlStageDefraLinks',
  defraLinksDelinked: 'etlStageDefraLinks',
  financeDAX: 'etlStageFinanceDax',
  financeDAXDelinked: 'etlStageFinanceDax',
  organisation: 'etlStageOrganisation',
  organisationDelinked: 'etlStageOrganisation',
  settlement: 'etlStageSettlement',
  tclcOption: 'etlStageTclcPiiPayClaimSfimtOption',
  tclc: 'etlStageTclcPiiPayClaimSfimt',
  appCalcResultsDelinkPayments: 'etlStageAppCalcResultsDelinkPayments',
  tdeLinkingTransferTransactions: 'etlStageTdeLinkingTransferTransactions',
  day0Organisation: 'etlStageDay0Organisation',
  day0BusinessAddress: 'etlStageDay0BusinessAddressContactV'
}
