module.exports = {
  appCalculationResultsDelinkPayments: 'etlStageAppCalcResultsDelinkPayments',
  applicationDetailDelinked: 'etlStageApplicationDetail',
  appsPaymentNotificationDelinked: 'etlStageAppsPaymentNotification',
  appsTypesDelinked: 'etlStageAppsTypes',
  businessAddressDelinked: 'etlStageBusinessAddressContactV',
  calculationsDetailsDelinked: 'etlStageCalculationDetails',
  cssContractApplicationsDelinked: 'etlStageCssContractApplications',
  cssContractDelinked: 'etlStageCssContracts',
  cssOptionsDelinked: 'etlStageCssOptions',
  defraLinksDelinked: 'etlStageDefraLinks',
  financeDAXDelinked: 'etlStageFinanceDax',
  organisationDelinked: 'etlStageOrganisation',
  settlement: 'etlStageSettlement',
  tclcOptionDelinked: 'etlStageTclcPiiPayClaimSfimtOption',
  tclcDelinked: 'etlStageTclcPiiPayClaimSfimt',
  appCalcResultsDelinkPayments: 'etlStageAppCalcResultsDelinkPayments',
  tdeLinkingTransferTransactions: 'etlStageTdeLinkingTransferTransactions',
  day0Organisation: 'etlStageDay0Organisation',
  day0BusinessAddress: 'etlStageDay0BusinessAddressContactV'
}
