{{- include "ffc-helm-library.cron-job" (list . "ffc-doc-statement-data.cron-job") -}}
{{- define "ffc-doc-statement-data.cron-job" -}}
spec:
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - {{ include "ffc-helm-library.container" (list . "ffc-doc-statement-data.container") | nindent 12 }}
{{- end -}}
